"""Add department field to users table

Revision ID: 654e6c68f54a
Revises: e03f385303fc
Create Date: 2025-10-03 23:28:57.209679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654e6c68f54a'
down_revision = 'e03f385303fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('department')

    # ### end Alembic commands ###
