"""empty message

Revision ID: 236ab0cdc05a
Revises: ed237f83f535
Create Date: 2025-07-30 00:03:39.410020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '236ab0cdc05a'
down_revision = 'ed237f83f535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purpose', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.drop_column('purpose')

    # ### end Alembic commands ###
