"""add_session_room_number_to_class_sessions

Revision ID: 6e33e4408b2e
Revises: b6249cca07bd
Create Date: 2025-12-01 20:13:18.844499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e33e4408b2e'
down_revision = 'b6249cca07bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_room_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_sessions', schema=None) as batch_op:
        batch_op.drop_column('session_room_number')

    # ### end Alembic commands ###
