"""Add time_in and time_out to InstructorAttendance

Revision ID: 89d5c34fd551
Revises: fa7a87188f06
Create Date: 2025-11-23 17:04:32.702545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89d5c34fd551'
down_revision = 'fa7a87188f06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.alter_column('term',
               existing_type=postgresql.ENUM('1st semester', '2nd semester', 'summer', name='term_enum'),
               nullable=True)
        batch_op.alter_column('school_year',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    with op.batch_alter_table('instructor_attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_in', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('time_out', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructor_attendance', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('time_out')
        batch_op.drop_column('time_in')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.alter_column('school_year',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
        batch_op.alter_column('term',
               existing_type=postgresql.ENUM('1st semester', '2nd semester', 'summer', name='term_enum'),
               nullable=False)

    # ### end Alembic commands ###
