"""Consolidate attendance records

Revision ID: b6249cca07bd
Revises: fedcba987654
Create Date: 2025-11-30 12:11:55.890022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b6249cca07bd'
down_revision = 'fedcba987654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_attendance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_attendance_records_date'))
        batch_op.drop_index(batch_op.f('ix_student_attendance_records_student_id'))

    op.drop_table('student_attendance_records')
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.alter_column('class_session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('PRESENT', 'ABSENT', 'LATE', 'EXCUSED', 'LEFT_EARLY', name='attendancestatus'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('PRESENT', 'ABSENT', 'LATE', 'EXCUSED', 'LEFT_EARLY', name='attendancestatus'),
               nullable=False)
        batch_op.alter_column('class_session_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('student_attendance_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('time_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('time_out', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('student_attendance_records_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('student_attendance_records_pkey'))
    )
    with op.batch_alter_table('student_attendance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_attendance_records_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_attendance_records_date'), ['date'], unique=False)

    # ### end Alembic commands ###
