"""add school_year to class model

Revision ID: e03f385303fc
Revises: 68b17c1e7a9b
Create Date: 2025-09-02 02:05:23.932309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e03f385303fc'
down_revision = '68b17c1e7a9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_year', sa.String(length=9), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('school_year')

    # ### end Alembic commands ###
