"""make term and school_year nullable in classes

Revision ID: abc123def456
Revises: 654e6c68f54a
Create Date: 2025-11-22 20:08:12.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc123def456'
down_revision = '654e6c68f54a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.alter_column('term', nullable=True)
        batch_op.alter_column('school_year', nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.alter_column('term', nullable=False)
        batch_op.alter_column('school_year', nullable=False)

    # ### end Alembic commands ###